name: crser-terraform-apply

permissions:
  id-token: write
  contents: write
  pull-requests: write

on:
  workflow_call:

env:
  # Replace with actual values
  IMAGE_NAME: PROVIDE_YOUR_IMAGE_NAME_HERE
  GCP_PROJECT_ID: PROVIDE_GCP_PROJECT_ID_HERE
  GCP_REGION: PROVIDE_GCP_REGION_HERE
  REPO_NAME: PROVIDE_REPO_NAME_HERE

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: 1.6.6

      - name: Fetch GCP Key
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          create_credentials_file: true
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT_EMAIL }}"

      - name: Set permissions for the credentials file
        run: chmod 644 $GOOGLE_APPLICATION_CREDENTIALS

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build \
            --target web-app \
            -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} \
            .
          docker tag \
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} \
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} 
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Terraform apply
        run: |
          cd ./terraform/cloud_run_service
          echo "Initializing Terraform..."
          terraform init

          echo "Validating Terraform..."
          terraform validate

          echo "Running Terraform plan..."
          terraform apply \
            -input=false \
            -auto-approve \
            -var="image_tag=${{ github.run_number }}" \
            -var="image_name=${{ env.IMAGE_NAME }}" \
            -var="project_id=${{ env.GCP_PROJECT_ID }}" \
            -var="region=${{ env.GCP_REGION }}" \
            -var="repo_name=${{ env.REPO_NAME }}"
